name: isogram
version: 1.7.0.8

dependencies:
  - base
  - text
  - containers

library:
  exposed-modules: Isogram
  source-dirs: src
  ghc-options: -Wall
    -XOverloadedStrings
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - isogram
      - hspec
